.job_template:
  interruptible: true
  before_script:
    - pip install virtualenv==20.0.18 --no-cache
    - virtualenv env
    - . ./env/bin/activate
    - pip install -r dev.requirements.txt --upgrade-strategy=eager --no-cache
  after_script:
    - . ./env/bin/activate
    - pip uninstall -y opyoid  # https://github.com/pypa/pip/issues/4537
  tags:
    - docker
  cache:
    policy: pull-push
    paths:
      - env/

.test-template:
  extends: .job_template
  stage: test
  script:
    - py.test --cov-report term --cov=opyoid ./tests ./tests_e2e
  coverage: '/\d+\%\s*$/'

test-3.6:
  extends: .test-template
  image: python:3.6-slim

test-3.7:
  extends: .test-template
  image: python:3.7-slim

test-3.8:
  extends: .test-template
  image: python:3.8-slim

test-3.9:
  extends: .test-template
  image: python:3.9-rc
  allow_failure: true

lint:
  extends: .job_template
  image: python:3.6-slim
  stage: test
  script:
    - pylint --load-plugins pylint_quotes opyoid
    - >
      pylint --load-plugins pylint_quotes ./tests ./tests_e2e
      --disable=too-many-public-methods,no-self-use,too-many-instance-attributes

deploy:
  extends: .job_template
  image: python:3.6-slim
  stage: deploy
  interruptible: false
  script:
    - |
      cat > ~/.pypirc << EOF
      [distutils]
      index-servers =
        pypi
        nexus

      [pypi] # https://www.python.org/pypi
      username:
      password:

      [nexus]
      repository: ${NEXUS_PYPI_PUSH_URL}
      username: ${NEXUS_PYPI_PUSH_USERNAME}
      password: ${NEXUS_PYPI_PUSH_PASSWORD}
      EOF
    - sed -i "s#version=\"DEV\",#version=\"${CI_COMMIT_TAG}\",#g" setup.py
    - python setup.py sdist bdist_wheel
    - twine upload -r nexus dist/opyoid-${CI_COMMIT_TAG}*
  only:
    - tags

stages:
  - test
  - deploy
